### ISSUE TITLE
Schematic request

### ISSUE THREAD

**Issue by rahilj** [tsaitsai/Connected-Pregnancy-Test#1]
Hi Eric

I am a graduate student at UW, Seattle. I need to demo a connected diagnostic test for a class I am teaching. I am interested in forking this project. Is it possible to share the schematics of the pins brought to the header, or some pictures of the inside of the test?

**Comment by rahilj** [comment]
https://www.hackster.io/erictsai/too-much-iot-tweeting-pregnancy-test-3922d1

**Comment by tsaitsai** [comment]
Hi jahilj.  The schematic is in the blog.  About half way down under the sub-heading "Light Blue Bean".  You see the 6 resistors.  That's it, very simple.

**Comment by rahilj** [comment]
Hi Eric

Thanks for the reply. I was able to find it eventually. 
Do you have the code for RPi? I see the nodes in the screenshot but having the code will be handy.

**Comment by tsaitsai** [comment]
The "code" for the Pi is just the Node-Red flows.  The only one that has
any scripting inside is the picture of the decode message node, so you can
just type that out from the image.  All other nodes are just configurations
you'll have to fill out for your own account info (your own twitter
account, or your own twilio account authentication info).

**Comment by rahilj** [comment]
I see. Sorry about the dumb questions. I haven't played with NodeRed before, always wanted to.

**Comment by tsaitsai** [comment]
No problem :)  I love Node Red, it's a great tool to have in your tool chest, and changes the way you approach projects.
